[package]
name = "date-zig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
quickcheck = "1.0.3"
time = { version = "0.3.21", features = ["quickcheck", "large-dates"] }


